# Generated by Django 5.0.7 on 2024-12-20 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Distance (km)')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_nearby', models.BooleanField(default=True, verbose_name='Is Nearby?')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='place_covers/', verbose_name='Cover Image Plase')),
                ('hotels', models.ManyToManyField(blank=True, related_name='places', to='Smart.hotel')),
                ('place_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Smart.placetype', verbose_name='Place Type')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='place_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_place', to='Smart.place')),
            ],
        ),
    ]
