# Generated by Django 5.0.7 on 2024-12-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart', '0002_placetype_place_placeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='place',
            name='hotels',
        ),
        migrations.RemoveField(
            model_name='place',
            name='is_nearby',
        ),
        migrations.CreateModel(
            name='PlaceHotelRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Distance (km)')),
                ('is_nearby', models.BooleanField(default=True, verbose_name='Is Nearby?')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_places', to='Smart.hotel')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_hotels', to='Smart.place')),
            ],
        ),
    ]
