# Generated by Django 5.0.7 on 2024-12-20 10:59

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Smart', '0003_remove_place_distance_remove_place_hotels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='loction',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='place',
            name='loction',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63),
        ),
    ]
