# Generated by Django 5.0.7 on 2024-12-20 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hauberge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('maison', 'Maison'), ('camp', 'Camp')], max_length=10)),
                ('capacite', models.IntegerField()),
                ('nom', models.CharField(max_length=255)),
                ('emplacement', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('nbr_personne_reserve', models.IntegerField()),
                ('disponibilite', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HaubergeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hauberge_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('hauberge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.hauberge')),
            ],
        ),
        migrations.CreateModel(
            name='HaubergeOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hauberge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='base.hauberge')),
            ],
        ),
    ]
