# Generated by Django 5.0.7 on 2024-12-20 08:36

import django.db.models.deletion
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('numero_carte_identite', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10)),
                ('numero_carte_identite', models.CharField(max_length=50, unique=True)),
                ('permission_parentale', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='hauberge',
            name='emplacement',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chambre', models.IntegerField()),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField()),
                ('nature_reservation', models.CharField(choices=[('Gratuit', 'Gratuit'), ('Non Gratuit', 'Non Gratuit')], max_length=20)),
                ('restauration_montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hauberge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hauberge')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.resident')),
            ],
        ),
        migrations.CreateModel(
            name='HaubergeResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hauberge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hauberge')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.resident')),
            ],
        ),
    ]
